### PR TITLE
feat(customizations): support dependencies between stacksets

### PR DESCRIPTION
**Pull request by allcloud-sahar-hagbi**
Hi,
Following our meeting which we discussed on this feature request, here is the pr. We need an ability to control stacksets order creation.
Thx.

### CODE REVIEW

**Comment by erwaxler** [comment]
Hi @allcloud-sahar-hagbi, thank you for your contribution to the Landing Zone Accelerator!

I know there was a meeting where a feature request regarding dependencies between StackSets was discussed. My perception was that the resolution of that meeting was that the feature to support dependencies between StackSets would not ultimately provide the desired behavior and was [closed](https://github.com/awslabs/landing-zone-accelerator-on-aws/pull/569).

To reiterate the discussion, while CloudFormation dependencies can be created between `AWS::CloudFormation::StackSet` resources, these dependencies do not affect the creation of the CloudFormation Stack resources provisioned by the StackSet. While we can show that a StackSet depends on another StackSet, this does not guarantee a dependency between the stack instances created by each StackSet.

For example, say a user defines `StackSet A` and `StackSet B`. Using this MR, `StackSet B` is set to explicitly depend on `StackSet A`. When 10 new users are created through LZA, the Customizations stack will first update the definition of `StackSet A` and update the deployment targets to the 10 new accounts. Before confirming successful creation the 10 new stack instances, the StackSet will respond to the CloudFormation service with `UPDATE_SUCCEEDED`. The 10 stack instances for StackSet A will be queued to be created in the new accounts. At this point, the same process will occur for `StackSet B`. The problem is, there is no mechanism to ensure the Stack Instance A will actually deploy in a new account before Stack Instance B. Numerous factors internal to the CloudFormation service may cause the creation of stack instance B to occur before stack instance A.

For the reasons above, we have deliberately not included a `runOrder` or `dependsOn` flag for use with CloudFormation StackSets and do not intend to add one until this issue is mitigated. For customers with requirements for dependencies between stacks, we recommend using `cloudFormationStacks`.

**Comment by allcloud-sahar-hagbi** [comment]
Hi @erwaxler , thank you for your fast response, I'm really appreciate it.
Yea, I remember you said this matter (inability to define order between stacksets) was the response to our feature request. Also, I closed the old PR according to your response. After the meeting, I tried to test this scenario. I tested that use case and **it actually works fine**. I provisioned a heavy StackSetA with a lot of stack instances and it was finished to provision completely (after almost 5-6 mins) before stackset B started to execute.
So, maybe I missed something here? Did you mean to something else maybe?

**Comment by erwaxler** [comment]
Hi @allcloud-sahar-hagbi , thank you for the additional context there, that helps explain it. I ran a test in my environment and observed similar results, my template took about 5 minutes to execute.

The root of my concern is documented in the [UpdateStackSet](https://docs.aws.amazon.com/AWSCloudFormation/latest/APIReference/API_UpdateStackSet.html) API documentation page:

```
Even if the stack set operation created by updating the stack set fails (completely or partially, below or above a specified failure tolerance), the stack set is updated with your changes.
```

My previous assumption was that behind the scenes, when performing an `UPDATE` operation on a `AWS::CloudFormation::StackSet` resource, the CloudFormation service performed an `UpdateStackSet` API call then changed the resource's status to `UPDATE_COMPLETE`.

After looking at the API calls in CloudTrail, it appears CloudFormation StackSets now performs a more complex logic flow where it first performs `UpdateStackSet`, then `CreateStackInstances` and `UpdateStackInstances` accordingly.

Since this behavior does now appear to wait for stack instances to be updated successfully, I am okay with adding this pattern to the LZA codebase. 

I am still somewhat concerned that I cannot find any documentation verifying this behavior for the `AWS::CloudFormation::StackSet` resource, but not concerned enough to block the feature. I think we just need to be more careful with our messaging. Instead of:

```
   * The order to deploy the stack relative to the other stacks. Can contain multiple stack names.
   * For any stackset name you define here, the stackset defined will be deployed before the current one.
```

I would like to see this changed to:

```
   * The other StackSets this StackSet depends on. For
   * For stackset names you define here, a CloudFormation DependsOn attribute will be added between the resources. Please note this does not guarantee the deployment order of the stack instances within the StackSet.
```

**Comment by allcloud-sahar-hagbi** [comment]
Hi @erwaxler , again, thx you for your immediate and fast response, it's really important to our roadmap migration to LZA's timeline.
First of all, I changed the description of the property as you asked for. I understand that you don't want to take any guarantee on any unexpected stackset's order deployment.
With your permission, I want to verify this issue once and for all against the CloudFormation team, via AWS Support service. I will open a support case for them on this topic and get back to you with an answer.

Secondly, with your approval, I believe we can proceed further with this PR and get into details. I will start from elaborating to you what I have done here.

As we understand together, this PR is meant for defining dependencies between stacksets.  I will describe it by the following categories:

**Config:**
`config/lib/models/customization-config.ts`:
added the property `dependsOn` to the ICloudFormationStackSet interface with your latest description.

`config/lib/customization-config.ts`:
added the property `dependsOn` to the CloudFormationStackSet class.


**Deployment:**
`customizations-stack.ts` file.
I have added to each stackset, his CfnStackSet object, its dependency defined under the `dependsOn` property.
This was done by the property `addDependency` of the CfnStackSet object.

**Validation**
`customizations-config-validator.ts`:
I have added two validation in two functions - `validateCircularDependencies` and `findCircularDependencyInSingleStack`.
The two functions above check two things:
1. Every stackset that contains the property `dependsOn`, the value of the property points out on an existing stackset, and not a dummy value.
2.  There is no circular dependency within any group of stacksets defined in customizations file, i.e. `Stackset A` dependsOn `StackSet B` dependsOn `StackSet C` dependsOn `StackSet A`.
A circular dependency can lead to a deadlock.

**Comment by erwaxler** [comment]
Hey @allcloud-sahar-hagbi thanks for doing that! And yes absolutely, if you could try to track down a definitive answer from the CloudFormation service team that would be much appreciated.

And thank you for the write-up, that all makes sense to me. I'll be away until early next week, but once I am back my plan is to run some additional tests using this branch. If all looks good, I think we have all the components we need to get this merged.

**Comment by allcloud-sahar-hagbi** [comment]
Hi @erwaxler , I am hoping you are enjoying your vacation and you're having a great time!
I started a correspondence about this matter with the CloudFormation team, and I've added you to the correspondence.

**Comment by erwaxler** [comment]
Hi @allcloud-sahar-hagbi , thank you very much! I did see the correspondence with the CloudFormation team, thank you for tracking down that information.

I'm pleased to say that all my internal testing was successful and I have merged this feature into the code base! Between releases code is managed outside of GitHub, so I will close this pull request in the meantime. This feature will be included in v1.10.0 of the LZA which is planned for release in the next few weeks.

Thank you again for your work contributing to the Landing Zone Accelerator!

**Pull request closed without merging**
